### ISSUE TITLE
API23 support

### ISSUE THREAD

**Issue by makkussu** [Tadashi-Hikari/Sapphire-Assistant-Framework#7]
As far as I can see, the app has no support for devices with API23 (Android 7.0 and greater) while the minimum is API24. Is there a possibility for supporting those devices? 

Tested on Honor 6A, Android 7.0

**Comment by Tadashi-Hikari** [comment]
It should work fine on Android 7.0 if the minimum API is updated in the build process. I didn't target 7.1 by default due to some significant Android changes, but I don't think there are any explicit issues with the libraries I am using. There is only one activity in the whole project, which is where I've seen most of the compatibility issues come from.

If you want to try to rebuild it at let me know what errors (if any) there were, I can look in to updating it incorporating the changes. Did you try it on your device and it didn't run at all?

**Comment by makkussu** [comment]
>Did you try it on your device and it didn't run at all?

I couldn't even install it. There was 'Problem parsing package' error, therefore I suppose the problem lies in the minimum API level set in program. 

>If you want to try to rebuild it 

I'll give it a try for sure. However, I am highly inexperienced in Android Development in general (I have basic knowledge but nothing more), therefore it will take some time for me to figure things out. Is that fine?

**Comment by Tadashi-Hikari** [comment]
Yeah, not a problem at all. The biggest thing is that you may have to change the minimum SDK in each build.gradle (there is one for each module). Let me know what happens
